// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestFirstProject.Contexts;

#nullable enable

namespace TestFirstProject.Migrations
{
    [DbContext(typeof(PersonsContext))]
    [Migration("20260419000001_AddEcommerceEntities")]
    partial class AddEcommerceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestFirstProject.Models.Person", b =>
            {
                b.Property<string>("Id").HasColumnType("text").HasColumnName("id");
                b.Property<int>("Age").HasColumnType("integer").HasColumnName("age");
                b.Property<string>("Name").IsRequired().HasMaxLength(14).HasColumnType("character varying(14)").HasColumnName("name");
                b.HasKey("Id");
                b.ToTable("users", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.AppUser", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("role");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("username");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("auth_users", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("LastMessageAt").HasColumnType("timestamp with time zone").HasColumnName("last_message_at");
                b.HasKey("Id");
                b.ToTable("conversations", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.Property<Guid>("ConversationId").HasColumnType("uuid").HasColumnName("conversation_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<DateTime>("JoinedAt").HasColumnType("timestamp with time zone").HasColumnName("joined_at");
                b.HasKey("ConversationId", "UserId");
                b.HasIndex("UserId");
                b.ToTable("conversation_participants", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Content").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)").HasColumnName("content");
                b.Property<Guid>("ConversationId").HasColumnType("uuid").HasColumnName("conversation_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<bool>("IsDeletedByRecipient").HasColumnType("boolean").HasColumnName("is_deleted_by_recipient");
                b.Property<bool>("IsDeletedBySender").HasColumnType("boolean").HasColumnName("is_deleted_by_sender");
                b.Property<bool>("IsRead").HasColumnType("boolean").HasColumnName("is_read");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");
                b.Property<Guid>("SenderId").HasColumnType("uuid").HasColumnName("sender_id");
                b.HasKey("Id");
                b.HasIndex("ConversationId");
                b.HasIndex("SenderId");
                b.ToTable("messages", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("body");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<bool>("IsRead").HasColumnType("boolean").HasColumnName("is_read");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("title");
                b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("type");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("notifications", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<bool>("NewMessageEnabled").HasColumnType("boolean").HasColumnName("new_message_enabled");
                b.Property<bool>("RoleChangedEnabled").HasColumnType("boolean").HasColumnName("role_changed_enabled");
                b.Property<bool>("SystemAlertEnabled").HasColumnType("boolean").HasColumnName("system_alert_enabled");
                b.Property<bool>("UserMentionedEnabled").HasColumnType("boolean").HasColumnName("user_mentioned_enabled");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("notification_preferences", (string)null);
            });

            // E-Commerce entities

            modelBuilder.Entity("TestFirstProject.Models.Category", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("description");
                b.Property<Guid?>("ParentCategoryId").HasColumnType("uuid").HasColumnName("parent_category_id");
                b.HasKey("Id");
                b.HasIndex("Name");
                b.HasIndex("ParentCategoryId");
                b.ToTable("categories", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Product", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("description");
                b.Property<string>("SKU").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("sku");
                b.Property<decimal>("BasePrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("base_price");
                b.Property<decimal>("Weight").HasPrecision(10, 3).HasColumnType("numeric(10,3)").HasColumnName("weight");
                b.Property<Guid>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                b.Property<string>("ImageUrls").HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("image_urls");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("SKU").IsUnique();
                b.HasIndex("CategoryId");
                b.HasIndex("BasePrice");
                b.HasIndex("IsActive");
                b.ToTable("products", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.ProductVariant", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<string>("SKU").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("sku");
                b.Property<string>("Size").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("size");
                b.Property<string>("Color").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("color");
                b.Property<string>("Material").HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("material");
                b.Property<decimal>("PriceDelta").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("price_delta");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("SKU").IsUnique();
                b.HasIndex("ProductId");
                b.ToTable("product_variants", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Warehouse", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
                b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("location");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean").HasColumnName("is_active");
                b.HasKey("Id");
                b.ToTable("warehouses", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.StockEntry", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductVariantId").HasColumnType("uuid").HasColumnName("product_variant_id");
                b.Property<Guid>("WarehouseId").HasColumnType("uuid").HasColumnName("warehouse_id");
                b.Property<int>("QuantityOnHand").HasColumnType("integer").HasColumnName("quantity_on_hand");
                b.Property<int>("QuantityReserved").HasColumnType("integer").HasColumnName("quantity_reserved");
                b.Property<int>("LowStockThreshold").HasDefaultValue(10).HasColumnType("integer").HasColumnName("low_stock_threshold");
                b.Property<DateTime>("LastUpdated").HasColumnType("timestamp with time zone").HasColumnName("last_updated");
                b.HasKey("Id");
                b.HasIndex("WarehouseId");
                b.HasIndex("ProductVariantId", "WarehouseId").IsUnique();
                b.ToTable("stock_entries", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.InventoryTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("StockEntryId").HasColumnType("uuid").HasColumnName("stock_entry_id");
                b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("type");
                b.Property<int>("QuantityChange").HasColumnType("integer").HasColumnName("quantity_change");
                b.Property<string>("Reason").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("reason");
                b.Property<Guid?>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<Guid?>("PerformedByUserId").HasColumnType("uuid").HasColumnName("performed_by_user_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("StockEntryId");
                b.HasIndex("OrderId");
                b.HasIndex("CreatedAt");
                b.ToTable("inventory_transactions", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.RestockRequest", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductVariantId").HasColumnType("uuid").HasColumnName("product_variant_id");
                b.Property<Guid>("WarehouseId").HasColumnType("uuid").HasColumnName("warehouse_id");
                b.Property<int>("RequestedQuantity").HasColumnType("integer").HasColumnName("requested_quantity");
                b.Property<int>("FulfilledQuantity").HasColumnType("integer").HasColumnName("fulfilled_quantity");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<Guid>("RequestedByUserId").HasColumnType("uuid").HasColumnName("requested_by_user_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("FulfilledAt").HasColumnType("timestamp with time zone").HasColumnName("fulfilled_at");
                b.HasKey("Id");
                b.HasIndex("Status");
                b.ToTable("restock_requests", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.ProductReview", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<int>("Rating").HasColumnType("integer").HasColumnName("rating");
                b.Property<string>("ReviewText").HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("review_text");
                b.Property<bool>("IsVerifiedPurchase").HasDefaultValue(false).HasColumnType("boolean").HasColumnName("is_verified_purchase");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.HasIndex("ProductId", "UserId").IsUnique();
                b.ToTable("product_reviews", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.PriceHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<decimal>("OldPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("old_price");
                b.Property<decimal>("NewPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("new_price");
                b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone").HasColumnName("changed_at");
                b.Property<Guid?>("ChangedByUserId").HasColumnType("uuid").HasColumnName("changed_by_user_id");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.HasIndex("ChangedAt");
                b.ToTable("price_history", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Cart", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid?>("AppliedCouponId").HasColumnType("uuid").HasColumnName("applied_coupon_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("LastActivityAt").HasColumnType("timestamp with time zone").HasColumnName("last_activity_at");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.HasIndex("LastActivityAt");
                b.ToTable("carts", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.CartItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("CartId").HasColumnType("uuid").HasColumnName("cart_id");
                b.Property<Guid>("ProductVariantId").HasColumnType("uuid").HasColumnName("product_variant_id");
                b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
                b.Property<DateTime>("AddedAt").HasColumnType("timestamp with time zone").HasColumnName("added_at");
                b.HasKey("Id");
                b.HasIndex("CartId", "ProductVariantId").IsUnique();
                b.ToTable("cart_items", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Order", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<string>("ShippingAddress").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("shipping_address");
                b.Property<string>("BillingAddress").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("billing_address");
                b.Property<decimal>("SubTotal").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("sub_total");
                b.Property<decimal>("DiscountAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("discount_amount");
                b.Property<decimal>("ShippingCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("shipping_cost");
                b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("total_amount");
                b.Property<string>("ShippingMethod").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("shipping_method");
                b.Property<Guid?>("CouponId").HasColumnType("uuid").HasColumnName("coupon_id");
                b.Property<int>("LoyaltyPointsUsed").HasColumnType("integer").HasColumnName("loyalty_points_used");
                b.Property<decimal>("LoyaltyDiscount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("loyalty_discount");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("notes");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<uint>("RowVersion").IsRowVersion().HasColumnType("xid").HasColumnName("row_version");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("Status");
                b.HasIndex("CreatedAt");
                b.HasIndex("UserId", "CreatedAt");
                b.ToTable("orders", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.OrderItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<Guid>("ProductVariantId").HasColumnType("uuid").HasColumnName("product_variant_id");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("product_name");
                b.Property<string>("VariantDescription").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("variant_description");
                b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
                b.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("unit_price");
                b.Property<decimal>("TotalPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("total_price");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.ToTable("order_items", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.OrderStatusHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<string>("FromStatus").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("from_status");
                b.Property<string>("ToStatus").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("to_status");
                b.Property<Guid>("ChangedByUserId").HasColumnType("uuid").HasColumnName("changed_by_user_id");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("notes");
                b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone").HasColumnName("changed_at");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("ChangedAt");
                b.ToTable("order_status_history", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Payment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<string>("Method").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("method");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("amount");
                b.Property<decimal>("RefundedAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("refunded_amount");
                b.Property<string>("TransactionReference").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("transaction_reference");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("CapturedAt").HasColumnType("timestamp with time zone").HasColumnName("captured_at");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("Status");
                b.ToTable("payments", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.PaymentAttempt", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("PaymentId").HasColumnType("uuid").HasColumnName("payment_id");
                b.Property<bool>("IsSuccessful").HasColumnType("boolean").HasColumnName("is_successful");
                b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("failure_reason");
                b.Property<string>("GatewayResponse").HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("gateway_response");
                b.Property<DateTime>("AttemptedAt").HasColumnType("timestamp with time zone").HasColumnName("attempted_at");
                b.HasKey("Id");
                b.HasIndex("PaymentId");
                b.ToTable("payment_attempts", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Wallet", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<decimal>("Balance").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("balance");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("wallets", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Shipment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<string>("Method").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("method");
                b.Property<string>("TrackingNumber").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("tracking_number");
                b.Property<string>("Carrier").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("carrier");
                b.Property<decimal>("ShippingCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("shipping_cost");
                b.Property<decimal>("WeightKg").HasPrecision(10, 3).HasColumnType("numeric(10,3)").HasColumnName("weight_kg");
                b.Property<string>("DistanceZone").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("distance_zone");
                b.Property<DateTime?>("ShippedAt").HasColumnType("timestamp with time zone").HasColumnName("shipped_at");
                b.Property<DateTime?>("EstimatedDeliveryDate").HasColumnType("timestamp with time zone").HasColumnName("estimated_delivery_date");
                b.Property<DateTime?>("DeliveredAt").HasColumnType("timestamp with time zone").HasColumnName("delivered_at");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("OrderId").IsUnique();
                b.HasIndex("TrackingNumber");
                b.ToTable("shipments", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Coupon", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("code");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("type");
                b.Property<decimal>("DiscountValue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("discount_value");
                b.Property<decimal?>("MinOrderValue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("min_order_value");
                b.Property<int?>("MaxUses").HasColumnType("integer").HasColumnName("max_uses");
                b.Property<int>("CurrentUses").HasColumnType("integer").HasColumnName("current_uses");
                b.Property<DateTime?>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.HasIndex("IsActive");
                b.ToTable("coupons", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.CouponUsage", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("CouponId").HasColumnType("uuid").HasColumnName("coupon_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<DateTime>("UsedAt").HasColumnType("timestamp with time zone").HasColumnName("used_at");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("CouponId", "UserId");
                b.ToTable("coupon_usages", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.LoyaltyTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<int>("Points").HasColumnType("integer").HasColumnName("points");
                b.Property<string>("Description").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("description");
                b.Property<Guid?>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("OrderId");
                b.ToTable("loyalty_transactions", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.FlashSale", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<decimal>("SalePrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("sale_price");
                b.Property<DateTime>("StartTime").HasColumnType("timestamp with time zone").HasColumnName("start_time");
                b.Property<DateTime>("EndTime").HasColumnType("timestamp with time zone").HasColumnName("end_time");
                b.Property<bool>("IsActive").HasDefaultValue(false).HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.ToTable("flash_sales", (string)null);
            });

            // Relationships for existing entities
            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation").WithMany("Participants").HasForeignKey("ConversationId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Conversation");
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation").WithMany("Messages").HasForeignKey("ConversationId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.AppUser", "Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Conversation");
                b.Navigation("Sender");
            });

            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithOne().HasForeignKey("TestFirstProject.Models.NotificationPreference", "UserId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("User");
            });

            // E-Commerce relationships
            modelBuilder.Entity("TestFirstProject.Models.Category", b =>
            {
                b.HasOne("TestFirstProject.Models.Category", "ParentCategory").WithMany("SubCategories").HasForeignKey("ParentCategoryId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("ParentCategory");
            });

            modelBuilder.Entity("TestFirstProject.Models.Product", b =>
            {
                b.HasOne("TestFirstProject.Models.Category", "Category").WithMany("Products").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Category");
            });

            modelBuilder.Entity("TestFirstProject.Models.ProductVariant", b =>
            {
                b.HasOne("TestFirstProject.Models.Product", "Product").WithMany("Variants").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Product");
            });

            modelBuilder.Entity("TestFirstProject.Models.StockEntry", b =>
            {
                b.HasOne("TestFirstProject.Models.ProductVariant", "ProductVariant").WithMany("StockEntries").HasForeignKey("ProductVariantId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.Warehouse", "Warehouse").WithMany("StockEntries").HasForeignKey("WarehouseId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("ProductVariant");
                b.Navigation("Warehouse");
            });

            modelBuilder.Entity("TestFirstProject.Models.InventoryTransaction", b =>
            {
                b.HasOne("TestFirstProject.Models.StockEntry", "StockEntry").WithMany().HasForeignKey("StockEntryId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("StockEntry");
            });

            modelBuilder.Entity("TestFirstProject.Models.RestockRequest", b =>
            {
                b.HasOne("TestFirstProject.Models.ProductVariant", "ProductVariant").WithMany().HasForeignKey("ProductVariantId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("TestFirstProject.Models.Warehouse", "Warehouse").WithMany().HasForeignKey("WarehouseId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("ProductVariant");
                b.Navigation("Warehouse");
            });

            modelBuilder.Entity("TestFirstProject.Models.ProductReview", b =>
            {
                b.HasOne("TestFirstProject.Models.Product", "Product").WithMany("Reviews").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Product");
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.PriceHistory", b =>
            {
                b.HasOne("TestFirstProject.Models.Product", "Product").WithMany("PriceHistories").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Product");
            });

            modelBuilder.Entity("TestFirstProject.Models.Cart", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.Coupon", "AppliedCoupon").WithMany().HasForeignKey("AppliedCouponId").OnDelete(DeleteBehavior.SetNull);
                b.Navigation("User");
                b.Navigation("AppliedCoupon");
            });

            modelBuilder.Entity("TestFirstProject.Models.CartItem", b =>
            {
                b.HasOne("TestFirstProject.Models.Cart", "Cart").WithMany("Items").HasForeignKey("CartId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.ProductVariant", "ProductVariant").WithMany().HasForeignKey("ProductVariantId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Cart");
                b.Navigation("ProductVariant");
            });

            modelBuilder.Entity("TestFirstProject.Models.Order", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("TestFirstProject.Models.Coupon", "Coupon").WithMany().HasForeignKey("CouponId").OnDelete(DeleteBehavior.SetNull);
                b.Navigation("User");
                b.Navigation("Coupon");
            });

            modelBuilder.Entity("TestFirstProject.Models.OrderItem", b =>
            {
                b.HasOne("TestFirstProject.Models.Order", "Order").WithMany("Items").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("TestFirstProject.Models.ProductVariant", "ProductVariant").WithMany().HasForeignKey("ProductVariantId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Order");
                b.Navigation("ProductVariant");
            });

            modelBuilder.Entity("TestFirstProject.Models.OrderStatusHistory", b =>
            {
                b.HasOne("TestFirstProject.Models.Order", "Order").WithMany("StatusHistory").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Order");
            });

            modelBuilder.Entity("TestFirstProject.Models.Payment", b =>
            {
                b.HasOne("TestFirstProject.Models.Order", "Order").WithMany("Payments").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Order");
            });

            modelBuilder.Entity("TestFirstProject.Models.PaymentAttempt", b =>
            {
                b.HasOne("TestFirstProject.Models.Payment", "Payment").WithMany("Attempts").HasForeignKey("PaymentId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Payment");
            });

            modelBuilder.Entity("TestFirstProject.Models.Shipment", b =>
            {
                b.HasOne("TestFirstProject.Models.Order", "Order").WithOne("Shipment").HasForeignKey("TestFirstProject.Models.Shipment", "OrderId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Order");
            });

            modelBuilder.Entity("TestFirstProject.Models.CouponUsage", b =>
            {
                b.HasOne("TestFirstProject.Models.Coupon", "Coupon").WithMany("Usages").HasForeignKey("CouponId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Coupon");
            });

            modelBuilder.Entity("TestFirstProject.Models.LoyaltyTransaction", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.FlashSale", b =>
            {
                b.HasOne("TestFirstProject.Models.Product", "Product").WithMany("FlashSales").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Product");
            });

            // Navigation collections
            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Navigation("Messages");
                b.Navigation("Participants");
            });

            modelBuilder.Entity("TestFirstProject.Models.Category", b =>
            {
                b.Navigation("Products");
                b.Navigation("SubCategories");
            });

            modelBuilder.Entity("TestFirstProject.Models.Product", b =>
            {
                b.Navigation("Variants");
                b.Navigation("Reviews");
                b.Navigation("PriceHistories");
                b.Navigation("FlashSales");
            });

            modelBuilder.Entity("TestFirstProject.Models.ProductVariant", b =>
            {
                b.Navigation("StockEntries");
            });

            modelBuilder.Entity("TestFirstProject.Models.Warehouse", b =>
            {
                b.Navigation("StockEntries");
            });

            modelBuilder.Entity("TestFirstProject.Models.Cart", b =>
            {
                b.Navigation("Items");
            });

            modelBuilder.Entity("TestFirstProject.Models.Order", b =>
            {
                b.Navigation("Items");
                b.Navigation("StatusHistory");
                b.Navigation("Payments");
                b.Navigation("Shipment");
            });

            modelBuilder.Entity("TestFirstProject.Models.Payment", b =>
            {
                b.Navigation("Attempts");
            });

            modelBuilder.Entity("TestFirstProject.Models.Coupon", b =>
            {
                b.Navigation("Usages");
            });

#pragma warning restore 612, 618
        }
    }
}
