// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestFirstProject.Contexts;

#nullable enable

namespace TestFirstProject.Migrations
{
    [DbContext(typeof(PersonsContext))]
    [Migration("20260418000001_AddMessagingAndNotifications")]
    partial class AddMessagingAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestFirstProject.Models.Person", b =>
            {
                b.Property<string>("Id")
                    .HasColumnName("id")
                    .HasColumnType("text");

                b.Property<int>("Age")
                    .HasColumnName("age")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnName("name")
                    .HasColumnType("character varying(14)");

                b.HasKey("Id");

                b.ToTable("users");
            });

            modelBuilder.Entity("TestFirstProject.Models.AppUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("username")
                    .HasColumnType("character varying(50)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("email")
                    .HasColumnType("character varying(255)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnName("password_hash")
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnName("role")
                    .HasColumnType("character varying(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnName("created_at")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("auth_users");
            });

            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnName("created_at")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("LastMessageAt")
                    .HasColumnName("last_message_at")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("LastMessageAt");

                b.ToTable("conversations");
            });

            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.Property<Guid>("ConversationId")
                    .HasColumnName("conversation_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("JoinedAt")
                    .HasColumnName("joined_at")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("ConversationId", "UserId");

                b.HasIndex("UserId");

                b.ToTable("conversation_participants");
            });

            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ConversationId")
                    .HasColumnName("conversation_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("SenderId")
                    .HasColumnName("sender_id")
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnName("content")
                    .HasColumnType("character varying(4000)");

                b.Property<bool>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("is_read")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnName("created_at")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnName("read_at")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDeletedBySender")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("is_deleted_by_sender")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("IsDeletedByRecipient")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("is_deleted_by_recipient")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.HasKey("Id");

                b.HasIndex("ConversationId");

                b.HasIndex("SenderId");

                b.HasIndex("CreatedAt");

                b.HasIndex("ConversationId", "CreatedAt");

                b.HasIndex("ConversationId", "IsRead");

                b.ToTable("messages");
            });

            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnName("type")
                    .HasColumnType("character varying(30)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnName("title")
                    .HasColumnType("character varying(200)");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnName("body")
                    .HasColumnType("character varying(2000)");

                b.Property<bool>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("is_read")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnName("created_at")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnName("read_at")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "IsRead");

                b.HasIndex("UserId", "CreatedAt");

                b.ToTable("notifications");
            });

            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<bool>("NewMessageEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("new_message_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("RoleChangedEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("role_changed_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("SystemAlertEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("system_alert_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("UserMentionedEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("user_mentioned_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("notification_preferences");
            });

            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation")
                    .WithMany("Participants")
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TestFirstProject.Models.AppUser", "User")
                    .WithMany("ConversationParticipants")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Conversation");
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation")
                    .WithMany("Messages")
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TestFirstProject.Models.AppUser", "Sender")
                    .WithMany("SentMessages")
                    .HasForeignKey("SenderId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Conversation");
                b.Navigation("Sender");
            });

            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User")
                    .WithMany("Notifications")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.HasOne("TestFirstProject.Models.AppUser", "User")
                    .WithOne("NotificationPreference")
                    .HasForeignKey("TestFirstProject.Models.NotificationPreference", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.AppUser", b =>
            {
                b.Navigation("ConversationParticipants");
                b.Navigation("SentMessages");
                b.Navigation("Notifications");
                b.Navigation("NotificationPreference");
            });

            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Navigation("Participants");
                b.Navigation("Messages");
            });
#pragma warning restore 612, 618
        }
    }
}
