// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestFirstProject.Contexts;

#nullable enable

namespace TestFirstProject.Migrations
{
    [DbContext(typeof(PersonsContext))]
    partial class PersonsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestFirstProject.Models.Person", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id");

                b.Property<int>("Age")
                    .HasColumnType("integer")
                    .HasColumnName("age");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("character varying(14)")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("users", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("revoked_at");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("token");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id");

                b.HasIndex("Token")
                    .IsUnique()
                    .HasDatabaseName("IX_auth_refresh_tokens_token");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_auth_refresh_tokens_user_id");

                b.ToTable("auth_refresh_tokens", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.Role", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("IX_auth_roles_name");

                b.ToTable("auth_roles", (string)null);

                b.HasData(
                    new
                    {
                        Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                        Name = "Admin"
                    },
                    new
                    {
                        Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                        Name = "User"
                    },
                    new
                    {
                        Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                        Name = "PremiumUser"
                    });
            });

            modelBuilder.Entity("TestFirstProject.Models.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("AccessFailedCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("access_failed_count");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("email");

                b.Property<bool>("EmailConfirmed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false)
                    .HasColumnName("email_confirmed");

                b.Property<string>("EmailVerificationToken")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("email_verification_token");

                b.Property<DateTime?>("EmailVerificationTokenExpiry")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("email_verification_token_expiry");

                b.Property<DateTime?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("lockout_end");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("password_hash");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("IX_auth_users_email");

                b.ToTable("auth_users", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.UserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("role_id");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("auth_user_roles", (string)null);
            });

            modelBuilder.Entity("TestFirstProject.Models.RefreshToken", b =>
            {
                b.HasOne("TestFirstProject.Models.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.UserRole", b =>
            {
                b.HasOne("TestFirstProject.Models.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TestFirstProject.Models.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.Role", b =>
            {
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("TestFirstProject.Models.User", b =>
            {
                b.Navigation("RefreshTokens");

                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
