// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestFirstProject.Contexts;

#nullable enable

namespace TestFirstProject.Migrations
{
    [DbContext(typeof(PersonsContext))]
    partial class PersonsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ----- Person -----
            modelBuilder.Entity("TestFirstProject.Models.Person", b =>
            {
                b.Property<string>("Id").HasColumnType("text").HasColumnName("id");
                b.Property<int>("Age").HasColumnType("integer").HasColumnName("age");
                b.Property<string>("Name").IsRequired().HasMaxLength(14).HasColumnType("character varying(14)").HasColumnName("name");
                b.HasKey("Id");
                b.ToTable("users");
            });

            // ----- User -----
            modelBuilder.Entity("TestFirstProject.Models.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email");
                b.Property<string>("EmailVerificationToken").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email_verification_token");
                b.Property<DateTime?>("EmailVerificationTokenExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("email_verification_token_expires_at");
                b.Property<int>("FailedLoginAttempts").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("failed_login_attempts");
                b.Property<bool>("IsEmailVerified").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_email_verified");
                b.Property<DateTime?>("LockoutEndAt").HasColumnType("timestamp with time zone").HasColumnName("lockout_end_at");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("IX_auth_users_email");
                b.ToTable("auth_users");
            });

            // ----- Role -----
            modelBuilder.Entity("TestFirstProject.Models.Role", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("name");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique().HasDatabaseName("IX_auth_roles_name");
                b.ToTable("auth_roles");
                b.HasData(
                    new { Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"), Name = "Admin" },
                    new { Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"), Name = "User" },
                    new { Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"), Name = "PremiumUser" }
                );
            });

            // ----- UserRole -----
            modelBuilder.Entity("TestFirstProject.Models.UserRole", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid>("RoleId").HasColumnType("uuid").HasColumnName("role_id");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("UserId").HasDatabaseName("IX_auth_user_roles_user_id");
                b.HasIndex("RoleId").HasDatabaseName("IX_auth_user_roles_role_id");
                b.ToTable("auth_user_roles");
            });

            // ----- RefreshToken -----
            modelBuilder.Entity("TestFirstProject.Models.RefreshToken", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                b.Property<bool>("IsRevoked").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_revoked");
                b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                b.Property<string>("Token").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("token");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.HasKey("Id");
                b.HasIndex("Token").IsUnique().HasDatabaseName("IX_auth_refresh_tokens_token");
                b.HasIndex("UserId").HasDatabaseName("IX_auth_refresh_tokens_user_id");
                b.ToTable("auth_refresh_tokens");
            });

            // ----- Conversation -----
            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("LastMessageAt").HasColumnType("timestamp with time zone").HasColumnName("last_message_at");
                b.HasKey("Id");
                b.HasIndex("LastMessageAt").HasDatabaseName("IX_conversations_last_message_at");
                b.ToTable("conversations");
            });

            // ----- ConversationParticipant -----
            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.Property<Guid>("ConversationId").HasColumnType("uuid").HasColumnName("conversation_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<DateTime>("JoinedAt").HasColumnType("timestamp with time zone").HasColumnName("joined_at");
                b.HasKey("ConversationId", "UserId");
                b.HasIndex("UserId").HasDatabaseName("IX_conversation_participants_user_id");
                b.HasIndex("ConversationId").HasDatabaseName("IX_conversation_participants_conversation_id");
                b.ToTable("conversation_participants");
            });

            // ----- Message -----
            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<Guid>("ConversationId").HasColumnType("uuid").HasColumnName("conversation_id");
                b.Property<Guid>("SenderId").HasColumnType("uuid").HasColumnName("sender_id");
                b.Property<string>("Content").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)").HasColumnName("content");
                b.Property<bool>("IsRead").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_read");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");
                b.Property<bool>("IsDeletedBySender").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_deleted_by_sender");
                b.Property<bool>("IsDeletedByRecipient").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_deleted_by_recipient");
                b.HasKey("Id");
                b.HasIndex(new[] { "ConversationId", "CreatedAt" }).HasDatabaseName("IX_messages_conversation_id_created_at");
                b.HasIndex(new[] { "ConversationId", "SenderId", "IsRead" }).HasDatabaseName("IX_messages_conversation_sender_is_read");
                b.HasIndex("SenderId").HasDatabaseName("IX_messages_sender_id");
                b.ToTable("messages");
            });

            // ----- Notification -----
            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<int>("Type").HasColumnType("integer").HasColumnName("type");
                b.Property<string>("Title").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("title");
                b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("body");
                b.Property<bool>("IsRead").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_read");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");
                b.Property<string>("ReferenceId").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("reference_id");
                b.HasKey("Id");
                b.HasIndex(new[] { "UserId", "CreatedAt" }).HasDatabaseName("IX_notifications_user_id_created_at");
                b.HasIndex(new[] { "UserId", "IsRead" }).HasDatabaseName("IX_notifications_user_id_is_read");
                b.ToTable("notifications");
            });

            // ----- NotificationPreference -----
            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<int>("NotificationType").HasColumnType("integer").HasColumnName("notification_type");
                b.Property<bool>("IsEnabled").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("is_enabled");
                b.HasKey("Id");
                b.HasIndex(new[] { "UserId", "NotificationType" }).IsUnique().HasDatabaseName("IX_notification_preferences_user_type");
                b.ToTable("notification_preferences");
            });

            // ----- Relationships -----
            modelBuilder.Entity("TestFirstProject.Models.RefreshToken", b =>
            {
                b.HasOne("TestFirstProject.Models.User", "User").WithMany("RefreshTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.UserRole", b =>
            {
                b.HasOne("TestFirstProject.Models.User", "User").WithMany("UserRoles").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TestFirstProject.Models.Role", "Role").WithMany("UserRoles").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
                b.Navigation("Role");
            });

            modelBuilder.Entity("TestFirstProject.Models.ConversationParticipant", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation").WithMany("Participants").HasForeignKey("ConversationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TestFirstProject.Models.User", "User").WithMany("ConversationParticipants").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Conversation");
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.Message", b =>
            {
                b.HasOne("TestFirstProject.Models.Conversation", "Conversation").WithMany("Messages").HasForeignKey("ConversationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TestFirstProject.Models.User", "Sender").WithMany("SentMessages").HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Conversation");
                b.Navigation("Sender");
            });

            modelBuilder.Entity("TestFirstProject.Models.Notification", b =>
            {
                b.HasOne("TestFirstProject.Models.User", "User").WithMany("Notifications").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("TestFirstProject.Models.NotificationPreference", b =>
            {
                b.HasOne("TestFirstProject.Models.User", "User").WithMany("NotificationPreferences").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            // ----- Navigations -----
            modelBuilder.Entity("TestFirstProject.Models.Conversation", b =>
            {
                b.Navigation("Messages");
                b.Navigation("Participants");
            });

            modelBuilder.Entity("TestFirstProject.Models.Role", b =>
            {
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("TestFirstProject.Models.User", b =>
            {
                b.Navigation("ConversationParticipants");
                b.Navigation("Notifications");
                b.Navigation("NotificationPreferences");
                b.Navigation("RefreshTokens");
                b.Navigation("SentMessages");
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
