using TestFirstProject.Repositories.Interfaces;

namespace TestFirstProject.Models
{
    /// <summary>
    /// Represents a book in the library.
    /// Soft-delete is handled via <see cref="ISoftDeletable"/>; deleted records
    /// are never physically removed from the <c>books</c> table.
    /// </summary>
    public class Book : ISoftDeletable
    {
        /// <summary>Primary key — generated by the database on insert.</summary>
        public Guid Id { get; set; }

        /// <summary>Full title of the book.</summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>Author name.</summary>
        public string Author { get; set; } = string.Empty;

        /// <summary>Year of publication.</summary>
        public int Year { get; set; }

        /// <summary>Genre / category (e.g. "Fiction", "Science").</summary>
        public string Genre { get; set; } = string.Empty;

        /// <summary>Soft-delete flag. When true the book is hidden from all read endpoints.</summary>
        public bool IsDeleted { get; set; } = false;

        /// <summary>UTC timestamp set on first insert.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>UTC timestamp updated on every change.</summary>
        public DateTime UpdatedAt { get; set; }
    }
}
